model: yac
environment_changes:
        choose_computer.name:
                mistral:
                        add_module_actions:
                                - "load autoconf/2.69"
                                - "load automake/1.16.1"
                ollie:
                        add_module_actions:
                                - "load automake"

config_files:
    coupling_xml:  coupling_xml
    coupling_xsd:  coupling_xsd

config_sources:
    coupling_xml:  "/work/ollie/nwieters/ESM/Test_esm_tools/esm_experiments/mynamelists/coupling.xml"
    coupling_xsd:  "/work/ollie/nwieters/ESM/Test_esm_tools/esm_experiments/mynamelists/coupling.xsd"

metadata:
    Information: "For more information about YAC please go to the webpage: https://dkrz-sw.gitlab-pages.dkrz.de/yac/index.html"
