components:
- oasis3-mct-2.8
- esm-interface-generic
- echam-6.3.04p1-esm-interface
- fesom-2.0-esm-interface
coupling_changes:
- sed -i '/FESOM_COUPLED/s/OFF/ON/g' fesom-2.0/CMakeLists.txt
- sed -i '/COUPLED_WITH_YAC/s/ON/OFF/g' fesom-2.0/CMakeLists.txt
- sed -i '/ECHAM6_COUPLED/s/OFF/ON/g' echam-6.3.04p1/CMakeLists.txt
- sed -i '/COUPLED_WITH_YAC/s/ON/OFF/g' echam-6.3.04p1/CMakeLists.txt
- sed -i '/YAC/s/ON/OFF/g' esm-interface/CMakeLists.txt
- sed -i '/OASIS/s/OFF/ON/g' esm-interface/CMakeLists.txt
