available_versions:
- 2.0-o
- '1.4'
- 2.0-esm-interface
- 2.0-paleodyn
- '2.0'
choose_version:
  '1.4':
    git-repository: https://gitlab.dkrz.de/modular_esm/fesom-1.4.git
    install_bins: bin/fesom
  '2.0':
    branch: 2.0.2
    git-repository:
    - https://gitlab.dkrz.de/FESOM/fesom2.git
    - github.com/FESOM/fesom2.git
    install_bins: bin/fesom.x
  2.0-esm-interface:
    branch: using_esm-interface_yac
    destination: fesom-2.0
    git-repository:
    - https://gitlab.dkrz.de/FESOM/fesom2.git
    install_bins: bin/fesom.x
  2.0-o:
    branch: oifs-deck
    git-repository:
    - https://gitlab.dkrz.de/FESOM/fesom2.git
    - github.com/FESOM/fesom2.git
    install_bins: bin/fesom.x
  2.0-paleodyn:
    branch: paleodyn_frozen
    destination: fesom-2.0
    git-repository:
    - https://gitlab.dkrz.de/FESOM/fesom2.git
    - github.com/FESOM/fesom2.git
    install_bins: bin/fesom.x
clean_command: ${defaults.clean_command}
comp_command: mkdir -p build; cd build; cmake ..;   make install
