model: esm-interface

namelist_dir: "${esm_namelist_dir}/esm-interface/"
namelists:
        - namelist.esmcouple

config_files:
        config: config

config_sources:
        config: "${namelist_dir}/namelist.esmcouple"

metadata:
        Institute: Alfred Wegener Institute
        Description: Coupling interface for a modular coupling approach of ESMs.
        Authors: Nadine Wieters (nadine.wieters@awi.de)
        Publications:
        License:
